apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: project1234/next-13
      docker:
        target: development
      sync:
        manual:
          - src: "**/*.*"
            dest: .
portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    localPort: 8080
