apiVersion: apps/v1
kind: Deployment
metadata:
  name: next13
  labels:
    app: next13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next13
  template:
    metadata:
      labels:
        app: next13
    spec:
      containers:
        - name: next13
          image: next13
          ports:
            - containerPort: 3000