import Sidebar from './components/Sidebar';
import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ display: 'flex', height: '100%', width: '100%' }}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body style={{ display: 'flex', height: '100%', width: '100%' }}>
        <div style={{ display: 'flex', height: '100%', width: '100%' }}>
          <Sidebar />
          {children}
        </div>
      </body>
    </html >
  )
}
