apiVersion: v1
kind: Pod
metadata:
  name: migration-001
spec:
  restartPolicy: Never
  containers:
    - name: migration-001
      image: alpine:latest
      command: ["/bin/sh","-c"]
      args:
        - apk --update add postgresql-client; 
          until pg_isready --host=postgres; do sleep 1; done;
          psql postgres://postgres:postgres@postgres:5432/postgres $(MIGRATION)
      env:
        - name: MIGRATION
          value: |
            << SQL
              CREATE TABLE todos (
                id TEXT NOT NULL PRIMARY KEY,
                text TEXT NOT NULL,
                completed BOOLEAN NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
              );
            SQL
